name: Notify Discord on New Issue

on:
  issues:
    types: [opened]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: |
            **New Support Ticket Created**
            - **Title:** ${{ github.event.issue.title }}
            - **User:** ${{ github.event.issue.user.login }}
            - **Link:** ${{ github.event.issue.html_url }}
