name: Insert Created Timestamp into Issue (Pretty Format)

on:
  issues:
    types: [opened, assigned, closed]

permissions:
  issues: write

jobs:
  add-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Insert created timestamp
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;

            const now = new Date();
            const options = {
              timeZone: 'America/Chicago',
              month: '2-digit',
              day: '2-digit',
              year: 'numeric',
              hour: '2-digit',
              minute: '2-digit',
              hour12: true
            };
            const formatter = new Intl.DateTimeFormat('en-US', options);
            const formattedDate = formatter.format(now);

            const bodyWithTimestamp = `**Ticket Created At:** ${formattedDate}\n\n${context.payload.issue.body}`;

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: bodyWithTimestamp
            });

      - name: Assign issue to myself
        if: github.event.action == 'opened'
        uses: pozil/auto-assign-issue@v1
        with:
          assignees: dessyfb  # ⬅️ Replace this with your actual GitHub username

  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Update issue status to "In Progress"
        if: github.event.action == 'assigned'
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const issue_body = context.payload.issue.body;
            const updated_body = `**Status:** In Progress\n\n${issue_body}`;

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: updated_body
            });

      - name: Update issue status to "Closed"
        if: github.event.action == 'closed'
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const issue_body = context.payload.issue.body;
            const updated_body = `**Status:** Closed\n\n${issue_body}`;

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: updated_body
            });
